(DM-3) Placeholder hiện số tiền đã nạp cá nhân
minevn/dotman pull request #31
Opened 2024-05-14 11:01 UTC by tranlong5252

## Nội dung
- Thêm class `PlayerData` để lấy data về số point của người chơi.
- Thêm placeholder để lấy số point của người chơi.
## Tests
- [ ] Parse placeholder.

2024-05-15 01:52 UTC, amadeusmz requested changes

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +        )
Chỗ này anh muốn select một lần kiểu `SELECT key, value FROM dotman_player_data` rồi associate thành map

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +         */
Cái docs này nọ anh tạo bằng copilot cho vui nên quên xóa, xóa ở đây với bên leaderboard giúp anh nha em  
(real men don't comment their code)

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +}
thêm hàng trống vào cuối file giúp anh

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +        // cập nhật dữ liệu top
xóa giúp anh comment này với comment tượng tự bên leaderboard luôn

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +const val PLAYER_DATA_EXPIRE = 1 * 60 * 1000L // 1 phút
sửa thành `PLAYER_DATA_UPDATE_INTERVAL`

2024-05-15 01:52 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/Expansion.kt
> +        if (params.startsWith("point_") && args.size >= 2) run data@{
sửa prefix thành `data_`

2024-05-15 08:05 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +         */
ok 💀

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +        )
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +         */
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +}
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +        // cập nhật dữ liệu top
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/PlayerData.kt
> +const val PLAYER_DATA_EXPIRE = 1 * 60 * 1000L // 1 phút
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:20 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/Expansion.kt
> +        if (params.startsWith("point_") && args.size >= 2) run data@{
Em chỉnh sửa xong chỗ này rồi nhé

2024-05-15 08:56 UTC, amadeusmz requested changes

2024-05-15 08:56 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/Expansion.kt
> +        }
- Bổ sung thêm placeholder này vào tài liệu README.md
- Bổ sung hình ảnh tests demo sử dụng db h2 và mysql
  - Cách test: gõ lệnh `/dotman manual` vài lần để ghi player data rồi test placeholder

2024-05-15 08:56 UTC, amadeusmz commented on dotman-plugin/src/main/java/net/minevn/dotman/database/PlayerDataDAO.kt
> +    }
- Để tối ưu hơn thì mình cho key của map là `Player`, rồi truyền tham số `Player` để lấy data, khỏi cần chuyển uuid qua string
  - Khi nào có nhu cầu lấy data cho offline players thì mình chuyển key thành `UUID` sau
- Thêm `.toMap()` ở line 68 để bên ngoài không cần `associate`

2024-05-16 01:52 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/database/PlayerDataDAO.kt
> +    }
Ok em chỉnh lại rồi nhé

2024-05-16 01:52 UTC, tranlong5252 commented on dotman-plugin/src/main/java/net/minevn/dotman/Expansion.kt
> +        }
Ok em chỉnh lại rồi nhé, còn phần test sẽ test lại sau

2024-05-16 14:58 UTC, amadeusmz commented
Kết quả test: placeholder hoạt động đúng như mong đợi khi sử dụng H2 hoặc MySQL.

![image](https://github.com/minevn/dotman/assets/15067059/09d6494d-f859-4e55-86e7-b7710d23ab17)

2024-05-16 14:58 UTC, amadeusmz approved these changes

2024-05-16 14:58 UTC, merged